version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.2
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-passwd}
        - MONGO_TESTDB_DATABASE=${MONGO_TESTDB_DATABASE}
        - MONGO_TESTDB_USERNAME=${MONGO_TESTDB_USERNAME}
        - MONGO_TESTDB_PASSWORD=${MONGO_TESTDB_PASSWORD}
    ports:
      - ${MOGODB_PORT:-27017}:27017
    volumes:
      - $PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/
      - $PWD/database-data:/data/db

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - ${MOGODB_EXPRESS_PORT:-8081}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-root}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME:-express}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD:-express}
      - ME_CONFIG_OPTIONS_EDITORTHEME=material-darker
    links:
      - 'mongo:mongo'
    depends_on:
      - 'mongo'
